### ISSUE TITLE
Application cannot find job defined by BatchConfig

### ISSUE THREAD

**Issue by Edern76** [grails-plugins/grails-spring-batch#3]
After setting up this plugin and creating the Spring Batch tables on a Grails 3.3.7 project, I tried to launch a simple job by doing the following : 

`grails-app/batch/SimpleJobBatchConfig.groovy` : 

```groovy
import myapp.PrintMessageTasklet;

beans {
    xmlns batch:"http://www.springframework.org/schema/batch"

    batch.job(id: 'simpleJob') {
        batch.step(id: 'logStart') {
            batch.tasklet(ref: 'printMessage')
        }
    }

    printMessage(PrintMessageTasklet) { bean ->
        bean.autowire = "byName"
    }
}
```

`grails-app/services/myapp/SimpleJobService.groovy` : 

```groovy
package myapp

import grails.gorm.transactions.Transactional
import org.springframework.batch.core.JobParameters

@Transactional
class SimpleJobService {

    def jobLauncher;
    def simpleJob;

    def launchSimpleJob() {
        jobLauncher.run(simpleJob, new JobParameters())
    }
}
```

`src/main/groovy/myapp/PrintMessageTasklet` : 

```groovy
package myapp

import org.springframework.batch.core.StepContribution
import org.springframework.batch.core.scope.context.ChunkContext
import org.springframework.batch.core.step.tasklet.Tasklet
import org.springframework.batch.repeat.RepeatStatus

class PrintMessageTasklet implements Tasklet {
    RepeatStatus execute(StepContribution stepContribution, ChunkContext chunkContext) {
        println "Test"
        return RepeatStatus.FINISHED
    }
}
```

However, when I run my app and try to access my service launchSimpleJob method, I get the following error : 

```
The Job must not be null.. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: The Job must not be null.
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:94)
	at myapp.SimpleJobService.$tt__launchSimpleJob(SimpleJobService.groovy:13)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at myapp.SimpleJobController.launch(SimpleJobController.groovy:9)
	... 14 common frames omitted
```

If I try to launch it using the springBatchService method, the returned map tells me that it couldn't find the job named 'simpleJob' despite me having defined it in the BatchConfig file.

**Comment by Edern76** [comment]
Fixed it, the plugin documentation was outdated, turns out my BatchConfing needed to be in the src/main/resources/batch folder instead of the grails-app/batch folder.

Also had to change @Transactional to @Transactional(propagation = Propagation.NOT_SUPPORTED) in my service.
